### ISSUE TITLE
单字衔接手感优化

### ISSUE THREAD

**Issue by Jacobax** [hanzi-chai/libchai#2]
对于单字手感优化，目前的算法似乎都只是独立地考虑单个字，字与字之间没有联系。
即使考虑了词手感，以2字词为例，AaAbBaBb并不能反映打单手感，实际行文中应当考虑相邻字的衔接手感，也就是（假设4码）AcAzBaBb所体现的手感。
目前折衷的做法，是将词都拆成2字，如：单字手感→单字、字手、手感，词编码规则改为AcAzBaBb，有简打简则依单字简码编码，词只算手感忽略重

**Comment by tansongchen** [comment]
https://github.com/hanzi-chai/libchai/commit/5955aa9769aa9ba2e6ebb7a033082271337d051d 已完成
